# Generated by Django 2.1.2 on 2019-07-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Канал ютуба или группа')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда писал')),
                ('email', models.TextField(blank=True, null=True, verbose_name='почта канала')),
            ],
            options={
                'verbose_name_plural': 'Каналы ютуба или группы',
                'verbose_name': 'Канал ютуба или группа',
                'ordering': ['-posted'],
            },
        ),
    ]
