# Generated by Django 2.1.2 on 2019-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanal',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='почта канала'),
        ),
    ]
