# Generated by Django 2.1.2 on 2019-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Сайт')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'ordering': ['-posted'],
                'verbose_name': 'Запись гостевой книги',
                'verbose_name_plural': 'Записи гостевой книги',
            },
        ),
    ]
